#!/bin/bash

echo "Uninstalling... Please wait for a moment."

depmod -a

update-initramfs -u -v -k $(uname -r) >/dev/null 2>&1

ibmadrivers=("host_cdev_drv" "host_kbox_drv" "host_veth_drv" "cdev_veth_drv" "host_edma_drv")
drivernum=0
while [ ${drivernum} -lt ${#ibmadrivers[@]} ]; do
    mods=( $(/sbin/lsmod | grep -wo "${ibmadrivers[${drivernum}]}") )
    if [ "${mods}" == "${ibmadrivers[${drivernum}]}" ]; then
        /sbin/rmmod "${ibmadrivers[${drivernum}]}" 2>&1
        if [ "$?" -ne 0 ]; then
            echo "Failed to uninstall the installed ${ibmadrivers[${drivernum}]} kernel module."
            echo "Please uninstall the installed ${ibmadrivers[${drivernum}]} kernel module manually or reboot the system."
        else
            echo "Uninstall the installed ${ibmadrivers[${drivernum}]} kernel module successfully."
        fi
    fi
    let drivernum++
done

echo "Uninstall ibma_driver package successfully."